language: ruby
sudo: false
rvm:
  - 2.3.1
  - 2.2.5
  - jruby
matrix:
  include:
    - rvm: 2.3.1
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.2.5
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.2.5
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: jruby
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: jruby
      gemfile: gemfiles/rails_5.0.gemfile
