language: ruby

sudo: false

matrix:
  include:
    - rvm: 2.3.1
      script:
        - bundle exec rake rubocop
    - rvm: 2.3.1
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.2.5
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.2.5
      gemfile: gemfiles/rails_5.0.gemfile
