# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e46bab444f4ba2b206737f0081cd72a0287794694605cb80e0447e44ae40bae7fd9fded978b1d8d8874272526911723c03c6d6c935f41fea23c14d7fc54de0fa

test:
  secret_key_base: b5d051df1da96fe39ce1338d3ed6105ed68337a8ee0f24898cfbbda717fb4be247a70e9c4901feea05e039322b6e205186eea643ca40a3d3e792c2cb313dde07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
